version: "3.4"

services:
  db:
    image: postgis/postgis:13-3.0-alpine
    volumes:
      - ${PWD}/var:/share
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=example
    ports:
      - 5432:5432
