[".pre-commit-config.yaml"]
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/hadialqattan/pycln"
rev = "v2.1.1"
[[".pre-commit-config.yaml".repos.hooks]]
id = "pycln"
args = [ "--all",]


[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/psf/black"
[[".pre-commit-config.yaml".repos.hooks]]
id = "black"


[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/isort"
[[".pre-commit-config.yaml".repos.hooks]]
id = "isort"


[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/flake8"
[[".pre-commit-config.yaml".repos.hooks]]
id = "flake8"
additional_dependencies = [ "flake8-blind-except", "flake8-bugbear", "flake8-comprehensions", "flake8-debugger", "flake8-isort", "flake8-polyfill", "flake8-pytest", "flake8-typing-imports", "yesqa",]


[[".pre-commit-config.yaml".repos]]
repo = "local"
[[".pre-commit-config.yaml".repos.hooks]]
id = "mypy"
args = [ "--show-error-codes",]
name = "mypy"
entry = "mypy"
require_serial = true
language = "python"


[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/commitizen-tools/commitizen"
[[".pre-commit-config.yaml".repos.hooks]]
id = "commitizen"
stages = [ "commit-msg",]


["setup.cfg".flake8]
ignore = "E203,D202,E501,W503"
max-line-length = 120
exclude = "node_modules"

["setup.cfg".isort]
profile = "black"
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
extra_standard_library = "arrow"
multi_line_output = 3
line_length = 120
include_trailing_comma = true

["setup.cfg".mypy]
disallow_untyped_defs = true
follow_imports = "silent"
disallow_any_unimported = true
ignore_missing_imports = true
disallow_untyped_decorators = true
disallow_untyped_calls = true
check_untyped_defs = true
strict_optional = true
strict_equality = true
implicit_reexport = true
no_implicit_optional = true
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
warn_return_any = true

[nitpick.meta]
name = "Commitizen (Python)"
url = "https://github.com/commitizen-tools/commitizen"

["pyproject.toml".tool.black]
target-version = [ "py310",]
line-length = 120
include = "\\.pyi?$"
preview = true
force_exclude = "(\n  /(\n    | migrations\n  )/\n  | urls\\.py\n)\n"

[nitpick.files.present]
"mypy.ini" = "Set up mypy configuration overides in mypy.ini"
