name: CI
on:
  push:
    branches:
      - release/*
      - develop
      - master
      - main
  pull_request: {}

permissions:
  id-token: write # Required for federated aws oidc
  contents: read
  actions: read
  pull-requests: write

jobs:
  ci:
    uses: uptick/actions/.github/workflows/ci.yaml@release/slack-error
    secrets: inherit
    with:
      aws: true
      python: true
      poetry: true
      command: make ci
