name: CI
on:
  push:
    branches:
      - release/*
      - develop
      - master
      - main
  pull_request: {}

permissions:
  id-token: write # Required for federated aws oidc
  contents: read
  actions: read
  pull-requests: write

jobs:
  ci:
    uses: uptick/actions/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      aws: true
      python: true
      poetry: true
      command: make ci


  build:
    name: Build
    needs: [ci]
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::305686791668:role/default-github-actions-ci-role
          role-session-name: subscription-manager-ci
          aws-region: ap-southeast-2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/aws-actions/amazon-ecr-login
      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build test image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha, mode=max
          push: true
          tags: 305686791668.dkr.ecr.ap-southeast-2.amazonaws.com/subscription-manager:${{ github.sha }}